### ISSUE TITLE
License and further development

### ISSUE THREAD

**Issue by AJenbo** [troelskn/php-tracer-weaver#1]
Hi, I'm working on reviving this very excellent tool. Can I mark the code as being under the MIT license (seams to be you preferred for other projects), and do you have an preferences for future development (should I take over maintenance or send you a pull request).

What I got done so fare:
Union types.
Analyze signature
PHP 7.1 support.

My plans for further development:
Modernice the code to use PRS-4 autoloading.
Port tests to phpunit.
Port to using nikic/PHP-Parser (or maybe Microsoft/tolerant-php-parser) for parsing and editing PHP.
Port to using Symfony Console Component for the CLI interface.
Add a progressbar.
Process folder.
Run as tracer as a webservice (for code that doesn't have a test or good way to run the code from a CLI).
Write documentation.

Any suggestions or requests for where to take to project?

**Comment by troelskn** [comment]
Hi Anders.

Yes, you can certainly consider the code MIT. I'll add a file to the project to make it "official".

As you can see, I haven't touched this project for a long time. I'm more than happy to let you develop it. I could make you a collaborator for a start?

**Comment by AJenbo** [comment]
Sounds good.

How do you feel about renaming the it to phpweaver, it's catchy and more cli friendly. The name seams to be mostly available except for a freelance developer that goes by that name.

**Comment by troelskn** [comment]
Sounds fine by me. I'm not sure if it's possible to rename a project on Github though or if we need to create a new project and push the repo to that.

**Comment by troelskn** [comment]
Turns out that was easy enough - project is now phpweaver.
