### ISSUE TITLE
Use Symfony Console Component for the CLI interface.

### ISSUE THREAD

**Issue by AJenbo** [troelskn/php-tracer-weaver#5]
It's a familiar interface for a lot of developers as many projects use it. It also helps with documenting how the tool is used and has lots of nice helper functions.

**Comment by AJenbo** [comment]
I have worked a bit on this:
![weaver](https://user-images.githubusercontent.com/204594/34050322-b90a3536-e1ba-11e7-94c0-71753343c369.png)

@troelskn What do you think about the parameters?

The biggest difference is that it now doesn't allow you to write to a specified file but only the original file, or output it directly in the terminal.
The reason for this is that it can now process directories as well as single files, complicating taking a specific file name as the output path.

**Comment by troelskn** [comment]
It's definitely nicer to have it as a cli app. I like that we can have both tools as sub-commands under the same executable as well.

On the single file vs. tree, if it's possible to do both that might be the most flexible?
