### ISSUE TITLE
Weave multiple files

### ISSUE THREAD

**Issue by AJenbo** [troelskn/php-tracer-weaver#7]
This could either be done by specifying a folder to work on, a lit of files or it could automatically identify the files to work on from the trace data.

**Comment by AJenbo** [comment]
For now I have made the weave command in my somfony-console branch accept a path to either a file or folder.

I don't think it would be a good idea to auto detect what files to work on based on the trace file. The trace lists the file that calls a function and not the file where the function is defined. We could still find all involved files via the include/require calls, but this would also cause us to process any library file which could be very undesirable. The file transformation is comparably cheep so it's probably also not worth limiting the list of files to process by this data either.

As for processing a list of files I prefer specifying folders, but it shoudn't be difficult for some one to add support for processing lists of files also :)

**Comment by troelskn** [comment]
I don't think we would need to support a list of files necessarily. The typical use case would probably be for a directory, but I could also see the need to target a single file. But I don't really see the need for just some files. Even if someone would need that, calling the tool multiple times with e.g. `find` + `xargs` would be a possibility. Let's keep things simple.

**Comment by AJenbo** [comment]
Actually it turns out that all i need to to for this was add InputArgument::IS_ARRAY to the argument definition (yay for Symfony). This is helpful with the main project where I use/test phpweaver at the moment and bring us more in line with how some other tools (phpstand) takes there arguments.
